#!/usr/bin/perl

#
# Be sure to make this script executable!
# eg> chmod +x apache_syslog
#

use Sys::Syslog;
  
my $SERVER_NAME = shift || 'www-log';
my $FACILITY = 'local2';
my $PRIORITY = 'info';
my $log = '';

Sys::Syslog::setlogsock('unix');
openlog ($SERVER_NAME, 'ndelay', $FACILITY);
while ($log = <STDIN>) {
    chomp($log);
    syslog($PRIORITY, $log);
}
closelog