#!/bin/bash
#
# Initiation script for node.js apps.
# /etc/init.d/kurunt (start|stop|restart)
# set as executable: chmod 0755 kurunt
#

APP=index
APP_NAME=kurunt
#DIR=/opt/kurunt
DIR=/var/www/kurunt
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NODE_PATH=/usr/local/lib/node_modules
NODE=/usr/local/bin/node

test -x $NODE || exit 0

function start_app {
	echo "Starting: $APP_NAME"
	if [ -f /proc/`cat $DIR/var/pids/$APP_NAME.pid`/exe ]; then
		echo "Already running! pid: `cat $DIR/var/pids/$APP_NAME.pid`"
		return 1
	fi	
	NODE_ENV=production nohup "$NODE" "$DIR/$APP.js" 1>>"$DIR/var/logs/$APP_NAME.log" 2>&1 &
	echo $! > "$DIR/var/pids/$APP_NAME.pid"
}

function stop_app {
	echo "Stoping: $APP_NAME"
	if [ -f /proc/`cat $DIR/var/pids/$APP_NAME.pid`/exe ]; then
		kill `cat $DIR/var/pids/$APP_NAME.pid`
	fi
}

function status_app {
	echo "Status: $APP_NAME"
	if [ -f /proc/`cat $DIR/var/pids/$APP_NAME.pid`/exe ]; then
		echo "Running pid: `cat $DIR/var/pids/$APP_NAME.pid`"
		return 1
	fi	
	echo "Not running."
}

case $1 in
   start)
		start_app ;;
    stop)
		stop_app ;;
    status)
		status_app ;;		
    restart)
		echo "Restarting: $APP_NAME"
		stop_app
		start_app
		;;
    *)
		echo "Usage: $APP_NAME {start|stop|status|restart}"
esac
exit 0